# Generated by Django 6.0 on 2025-12-22 07:47

import applications.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("age", models.IntegerField(null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("gender", models.CharField(max_length=20, null=True)),
                ("marital_status", models.CharField(max_length=20, null=True)),
                ("community", models.CharField(max_length=100, null=True)),
                ("caste", models.CharField(max_length=100, null=True)),
                ("pan_number", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_primary", models.CharField(max_length=100, null=True)),
                ("phone_secondary", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=applications.utils.candidate_profile_path,
                    ),
                ),
                ("address", models.TextField()),
                ("total_experience_years", models.IntegerField(null=True)),
                ("present_post_years", models.IntegerField(null=True)),
                (
                    "mother_name_and_occupation",
                    models.CharField(max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LevelOfEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_attempted", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Login Log",
                "verbose_name_plural": "Admin Login Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_type", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[("FORM_SUBMITTED", "Form Submitted")], max_length=50
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademicExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("joining_date", models.DateField(null=True)),
                ("relieving_date", models.CharField(blank=True, max_length=50)),
                ("years", models.IntegerField(null=True)),
                ("months", models.IntegerField(null=True)),
                ("days", models.IntegerField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments",
                        to="applications.degree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="candidate_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20, null=True)),
                ("degree", models.CharField(max_length=100, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("year_of_passing", models.CharField(max_length=10, null=True)),
                ("institution", models.CharField(max_length=200, null=True)),
                ("university", models.CharField(max_length=200, null=True)),
                ("percentage", models.CharField(max_length=20, null=True)),
                ("class_obtained", models.CharField(max_length=50, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndustryExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("nature_of_work", models.CharField(max_length=200)),
                ("joining_date", models.DateField(null=True)),
                ("relieving_date", models.DateField(null=True)),
                ("years", models.IntegerField(null=True)),
                ("months", models.IntegerField(null=True)),
                ("days", models.IntegerField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_applied",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "present_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "present_organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("assistant_professor_years", models.PositiveIntegerField(default=0)),
                ("associate_professor_years", models.PositiveIntegerField(default=0)),
                ("professor_years", models.PositiveIntegerField(default=0)),
                ("other_years", models.PositiveIntegerField(default=0)),
                ("research_experience_years", models.PositiveIntegerField(default=0)),
                ("industry_experience_years", models.PositiveIntegerField(default=0)),
                ("journal_publications", models.PositiveIntegerField(default=0)),
                ("conference_publications", models.PositiveIntegerField(default=0)),
                ("students_guided_completed", models.PositiveIntegerField(default=0)),
                ("students_guided_ongoing", models.PositiveIntegerField(default=0)),
                (
                    "community_and_caste",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_type", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50, null=True)),
                ("count", models.IntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammesPublications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmes",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "publications",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "research_publications_details",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                ("research_scholars_details", models.TextField(blank=True, null=True)),
                (
                    "sponsored_projects",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "memberships",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                ("awards", models.CharField(default="", max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes_publications",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("indexing", models.CharField(max_length=100, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=50)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("institute", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode_ug", models.CharField(blank=True, max_length=30, null=True)),
                ("mode_pg", models.CharField(blank=True, max_length=30, null=True)),
                ("mode_phd", models.CharField(blank=True, max_length=30, null=True)),
                ("arrears_ug", models.IntegerField(blank=True, null=True)),
                ("arrears_pg", models.IntegerField(blank=True, null=True)),
                ("gate_score", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "net_slet_score",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("me_thesis_title", models.TextField(blank=True, null=True)),
                ("phd_thesis_title", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsoredProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                ("agency", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("subject_and_result", models.CharField(max_length=200)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_type", models.CharField(max_length=50)),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="application_ip_addr_2599b9_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="application_timesta_2dcdca_idx"
                    ),
                ],
            },
        ),
    ]
