# Generated by Django 5.2.6 on 2025-12-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("marital_status", models.CharField(max_length=20)),
                ("community", models.CharField(max_length=50)),
                ("caste", models.CharField(max_length=50)),
                ("pan_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone_primary", models.CharField(max_length=15)),
                ("phone_secondary", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField()),
                ("photo", models.ImageField(upload_to="candidate_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AcademicExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                ("years", models.PositiveIntegerField()),
                ("months", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=200)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="candidate_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("SSLC", "SSLC"),
                            ("HSC", "HSC"),
                            ("UG", "UG"),
                            ("PG", "PG"),
                            ("PHD", "PhD"),
                            ("POSTDOC", "Post Doctoral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("degree_name", models.CharField(max_length=100)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("institution", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("year_of_passing", models.CharField(max_length=10)),
                ("percentage", models.CharField(max_length=10)),
                ("class_obtained", models.CharField(max_length=50)),
                ("mode_of_study", models.CharField(max_length=10)),
                ("arrears", models.PositiveIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("count", models.PositiveIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndustryExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("nature_of_work", models.CharField(max_length=200)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("years", models.PositiveIntegerField()),
                ("months", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("current_designation", models.CharField(max_length=150)),
                ("current_organization", models.CharField(max_length=200)),
                ("years_experience", models.PositiveIntegerField()),
                ("applied_date", models.DateField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("publication_type", models.CharField(max_length=50)),
                ("indexing", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=10)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200)),
                ("level", models.CharField(max_length=10)),
                ("result_percentage", models.CharField(max_length=10)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
    ]
