# Generated by Django 6.0 on 2025-12-22 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammesPublications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programmes", models.JSONField(default=list)),
                ("publications", models.JSONField(default=list)),
                ("research_publications_details", models.JSONField(default=list)),
                ("research_scholars_details", models.TextField(blank=True, null=True)),
                ("sponsored_projects", models.JSONField(default=list)),
                ("memberships", models.JSONField(default=list)),
                ("awards", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes_publications",
                        to="applications.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Programmes and Publications",
            },
        ),
    ]
