# Generated by Django 6.0 on 2025-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="degree",
            old_name="name",
            new_name="degree",
        ),
        migrations.AddField(
            model_name="degree",
            name="degree_code",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
