# Generated by Django 6.0 on 2025-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipation",
            name="count",
        ),
        migrations.AddField(
            model_name="eventparticipation",
            name="number_of_events",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="years_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(max_length=500),
        ),
    ]
