# Generated by Django 6.0 on 2025-12-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_programmespublications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchdetails",
            name="arrears_pg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="arrears_ug",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="mode_pg",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="mode_phd",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="mode_ug",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
