# Generated by Django 5.2.1 on 2025-12-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_degree_department_designation_levelofeducation"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="department",
            name="degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="applications.degree",
            ),
        ),
    ]
