# Generated by Django 6.0 on 2025-12-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_rename_name_degree_degree_degree_degree_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="levelofeducation",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
