# Generated by Django 6.0 on 2025-12-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_remove_eventparticipation_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipation",
            name="candidate",
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="role",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="positionapplication",
            old_name="position",
            new_name="community_and_caste",
        ),
        migrations.RenameField(
            model_name="teachingsubject",
            old_name="subject_name",
            new_name="subject_and_result",
        ),
        migrations.RemoveField(
            model_name="academicexperience",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="academicexperience",
            name="to_date",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="education",
            name="arrears",
        ),
        migrations.RemoveField(
            model_name="education",
            name="degree_level",
        ),
        migrations.RemoveField(
            model_name="education",
            name="degree_name",
        ),
        migrations.RemoveField(
            model_name="education",
            name="mode_of_study",
        ),
        migrations.RemoveField(
            model_name="industryexperience",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="industryexperience",
            name="to_date",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="applied_date",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="current_designation",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="current_organization",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="years_experience",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="publication_type",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="year",
        ),
        migrations.RemoveField(
            model_name="teachingsubject",
            name="result_percentage",
        ),
        migrations.AddField(
            model_name="academicexperience",
            name="joining_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="academicexperience",
            name="relieving_date",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="candidate",
            name="mother_name_and_occupation",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="present_post_years",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="total_experience_years",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="category",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="industryexperience",
            name="joining_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="industryexperience",
            name="relieving_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="assistant_professor_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="associate_professor_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="conference_publications",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="industry_experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="journal_publications",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="other_years",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="position_applied",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="present_designation",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="present_organization",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="professor_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="research_experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="students_guided_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="students_guided_ongoing",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="days",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="months",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="years",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="caste",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="community",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="gender",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="marital_status",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="pan_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone_primary",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="class_obtained",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="percentage",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="university",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="year_of_passing",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="days",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="months",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="years",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="specialization",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="indexing",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="referee",
            name="contact_number",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_type", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50, null=True)),
                ("count", models.IntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode_ug", models.CharField(max_length=10, null=True)),
                ("mode_pg", models.CharField(max_length=10, null=True)),
                ("mode_phd", models.CharField(max_length=20, null=True)),
                ("arrears_ug", models.IntegerField(default=0)),
                ("arrears_pg", models.IntegerField(default=0)),
                ("gate_score", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "net_slet_score",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("me_thesis_title", models.TextField(blank=True, null=True)),
                ("phd_thesis_title", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="EventParticipation",
        ),
    ]
