# Generated by Django 6.0 on 2025-12-22 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_researchdetails_arrears_pg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionapplication",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="assistant_professor_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="associate_professor_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="community_and_caste",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="conference_publications",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="industry_experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="journal_publications",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="other_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="position_applied",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="present_designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="present_organization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="professor_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="research_experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="specialization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="students_guided_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="students_guided_ongoing",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=50)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("institute", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsoredProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                ("agency", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
    ]
