# Generated by Django 6.0 on 2025-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_eventparticipation_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone_primary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone_secondary",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
