# Generated by Django 6.0 on 2025-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_candidate_phone_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="candidate_photos/"
            ),
        ),
    ]
