# Generated by Django 6.0 on 2025-12-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_positionapplication_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programmespublications",
            options={},
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
