# Generated by Django 6.0 on 2025-12-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_programmespublications_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmespublications",
            name="awards",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="memberships",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="programmes",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="publications",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="research_publications_details",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programmespublications",
            name="sponsored_projects",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
    ]
