# Generated by Django 6.0 on 2025-12-23 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_academicexperience_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicexperience",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="institution",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="relieving_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="academicexperience",
            name="years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="present_post_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="total_experience_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="candidate_documents/"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="nature_of_work",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="organization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="assistant_professor_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="associate_professor_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="conference_publications",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="industry_experience_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="journal_publications",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="other_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="position_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applications.designation",
            ),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="present_designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="professor_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="research_experience_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="students_guided_completed",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="positionapplication",
            name="students_guided_ongoing",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="programme_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="qualification",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referee",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="referee",
            name="designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="referee",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="referee",
            name="organization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="arrears_pg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="arrears_ug",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchdetails",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="sponsoredproject",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="sponsoredproject",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teachingsubject",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applications.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="teachingsubject",
            name="level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="teachingsubject",
            name="subject_and_result",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
