# Generated by Django 6.0 on 2025-12-22 06:55

import applications.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_programmespublications_awards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=applications.utils.candidate_photo_path
            ),
        ),
    ]
