# Generated by Django 6.0 on 2025-12-23 06:38

import applications.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_alter_academicexperience_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.utils.candidate_document_path,
            ),
        ),
    ]
