# Generated by Django 6.0 on 2025-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_alter_document_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degree",
            options={
                "ordering": ["degree"],
                "verbose_name": "Degree",
                "verbose_name_plural": "Degrees",
            },
        ),
        migrations.AlterField(
            model_name="degree",
            name="degree",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="degree",
            name="degree_code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
