# Generated by Django 6.0 on 2025-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_alter_degree_options_alter_degree_degree_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degree",
            options={"ordering": ["degree"]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["degree", "name"]},
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name="degree",
            index=models.Index(
                fields=["degree_code"], name="application_degree__72a548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="degree",
            index=models.Index(fields=["degree"], name="application_degree_13dbae_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="application_name_7eff2e_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="application_code_a1b958_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["degree"], name="application_degree__264765_idx"
            ),
        ),
    ]
