# Generated by Django 6.0 on 2025-12-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_degree_options_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate_permission",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_permissions",
                to="applications.department",
            ),
        ),
        migrations.AlterField(
            model_name="certificate_permission",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_permissions",
                to="applications.document_type",
            ),
        ),
    ]
