# Generated by Django 5.2.5 on 2025-12-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_alter_certificate_permission_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applications.degree",
            ),
        ),
    ]
