# Generated by Django 5.2.5 on 2025-12-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_alter_qualification_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applications.levelofeducation",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applications.degree",
            ),
        ),
    ]
